"""Update timezones

Revision ID: 57bb93ae0b22
Revises: 949251ff383c
Create Date: 2026-01-26 21:09:09.620129

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57bb93ae0b22"
down_revision: str | Sequence[str] | None = "949251ff383c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "channel",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "channel_message",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message_statistic",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_statistic",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "media",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.add_column(
        "parsing_task", sa.Column("url", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "parsing_task",
        "last_parsed_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "parsing_task",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.drop_index(op.f("ix_parsing_task_link"), table_name="parsing_task")
    op.create_index(op.f("ix_parsing_task_url"), "parsing_task", ["url"], unique=True)
    op.drop_column("parsing_task", "link")
    op.alter_column(
        "telegram_client",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "telegram_client",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "telegram_client_proxy",
        "recorded_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "telegram_client_proxy",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_client_proxy",
        "updated_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "telegram_client_proxy",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "telegram_client",
        "updated_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "telegram_client",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.add_column(
        "parsing_task", sa.Column("link", sa.String(length=255), nullable=False)
    )
    op.drop_index(op.f("ix_parsing_task_url"), table_name="parsing_task")
    op.create_index(op.f("ix_parsing_task_link"), "parsing_task", ["link"], unique=True)
    op.alter_column(
        "parsing_task",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "parsing_task",
        "last_parsed_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_column("parsing_task", "url")
    op.alter_column(
        "media",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_statistic",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message_statistic",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message",
        "updated_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel_message",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "channel",
        "updated_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    op.alter_column(
        "channel",
        "recorded_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("(now())"),
    )
    # ### end Alembic commands ###
