"""Add file name to media model

Revision ID: 5a81eceb1bdf
Revises: fd36ffa275e8
Create Date: 2026-01-22 22:26:44.542396

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a81eceb1bdf"
down_revision: str | Sequence[str] | None = "fd36ffa275e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media", sa.Column("file_name", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "file_name")
    # ### end Alembic commands ###
