"""add worker account usage and session string

Revision ID: 5cd29f17000c
Revises: c5603e70cc81
Create Date: 2026-02-28 01:27:37.475223

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cd29f17000c"
down_revision: str | Sequence[str] | None = "c5603e70cc81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_account_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("worker_id", sa.String(length=255), nullable=False),
        sa.Column(
            "taken_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"], ["telegram_client.telegram_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "message_media_link_message_id_fkey", "message_media_link", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "message_media_link",
        "channel_message",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "telegram_client", sa.Column("session_string", sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_client", "session_string")
    op.drop_constraint(None, "message_media_link", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_media_link_ibfk_2"),
        "message_media_link",
        "channel_message",
        ["message_id"],
        ["id"],
    )
    op.drop_table("worker_account_usage")
    # ### end Alembic commands ###
