"""Remove useless field from telegram client table

Revision ID: 63fcf8111eed
Revises: dbf203c6f610
Create Date: 2026-01-24 14:03:20.587984

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63fcf8111eed"
down_revision: str | Sequence[str] | None = "dbf203c6f610"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_client", "lang_pack")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_client",
        sa.Column("lang_pack", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###
