"""Add parsing task model

Revision ID: 949251ff383c
Revises: 63fcf8111eed
Create Date: 2026-01-26 19:37:28.799882

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "949251ff383c"
down_revision: str | Sequence[str] | None = "63fcf8111eed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsing_task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("bucket", sa.Integer(), nullable=False),
        sa.Column("last_parsed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("bucket >= 0 AND bucket < 1440", name="check_bucket_range"),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsing_task_channel_id"), "parsing_task", ["channel_id"], unique=False
    )
    op.create_index(op.f("ix_parsing_task_link"), "parsing_task", ["link"], unique=True)
    op.drop_index(op.f("ix_channel_link"), table_name="channel")
    op.drop_column("channel", "link")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel", sa.Column("link", mysql.VARCHAR(length=255), nullable=False)
    )
    op.create_index(op.f("ix_channel_link"), "channel", ["link"], unique=True)
    op.drop_index(op.f("ix_parsing_task_link"), table_name="parsing_task")
    op.drop_index(op.f("ix_parsing_task_channel_id"), table_name="parsing_task")
    op.drop_table("parsing_task")
    # ### end Alembic commands ###
