"""add more stats

Revision ID: d2c2fc33083a
Revises: 3bc288e7abd5
Create Date: 2026-03-10 00:41:57.032785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2c2fc33083a"
down_revision: str | Sequence[str] | None = "3bc288e7abd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    new_columns = [
        "views_24h",
        "views_48h",
        "views_72h",
        "views_96h",
        "views_120h",
        "views_144h",
        "views_168h",
        "posts_count_24h",
        "posts_count_48h",
        "posts_count_72h",
        "posts_count_96h",
        "posts_count_120h",
        "posts_count_144h",
        "posts_count_168h",
    ]

    for col_name in new_columns:
        op.add_column(
            "channel_statistic",
            sa.Column(col_name, sa.Integer(), server_default="0", nullable=False),
        )
    for col_name in new_columns:
        op.alter_column("channel_statistic", col_name, server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_statistic", "posts_count_168h")
    op.drop_column("channel_statistic", "posts_count_144h")
    op.drop_column("channel_statistic", "posts_count_120h")
    op.drop_column("channel_statistic", "posts_count_96h")
    op.drop_column("channel_statistic", "posts_count_72h")
    op.drop_column("channel_statistic", "posts_count_48h")
    op.drop_column("channel_statistic", "posts_count_24h")
    op.drop_column("channel_statistic", "views_168h")
    op.drop_column("channel_statistic", "views_144h")
    op.drop_column("channel_statistic", "views_120h")
    op.drop_column("channel_statistic", "views_96h")
    op.drop_column("channel_statistic", "views_72h")
    op.drop_column("channel_statistic", "views_48h")
    op.drop_column("channel_statistic", "views_24h")
    # ### end Alembic commands ###
