"""Add locked_until and reason usage columns

Revision ID: d47bd9ff611b
Revises: d9964358c36d
Create Date: 2026-03-01 22:33:06.809549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d47bd9ff611b"
down_revision: str | Sequence[str] | None = "d9964358c36d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_account_usage",
        sa.Column("locked_until", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "worker_account_usage",
        sa.Column("reason", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "worker_account_usage",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("worker_account_usage", "taken_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_account_usage",
        sa.Column(
            "taken_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
    )
    op.drop_column("worker_account_usage", "created_at")
    op.drop_column("worker_account_usage", "reason")
    op.drop_column("worker_account_usage", "locked_until")
    # ### end Alembic commands ###
