"""nullable session string

Revision ID: d9964358c36d
Revises: 5cd29f17000c
Create Date: 2026-02-28 03:26:53.754750

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d9964358c36d"
down_revision: str | Sequence[str] | None = "5cd29f17000c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_client", "session_string", existing_type=mysql.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_client", "session_string", existing_type=mysql.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
