"""Add telegram client models

Revision ID: dbf203c6f610
Revises: 5a81eceb1bdf
Create Date: 2026-01-23 01:08:49.922560

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbf203c6f610"
down_revision: str | Sequence[str] | None = "5a81eceb1bdf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_client",
        sa.Column("telegram_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.String(length=255), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.Column("api_id", sa.BigInteger(), nullable=False),
        sa.Column("api_hash", sa.String(length=255), nullable=False),
        sa.Column("device_model", sa.String(length=255), nullable=False),
        sa.Column("system_version", sa.String(length=50), nullable=False),
        sa.Column("app_version", sa.String(length=50), nullable=False),
        sa.Column("lang_code", sa.String(length=10), nullable=False),
        sa.Column("system_lang_code", sa.String(length=10), nullable=False),
        sa.Column("lang_pack", sa.String(length=255), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "telegram_client_proxy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_client_id", sa.BigInteger(), nullable=False),
        sa.Column("proxy_type", sa.String(length=10), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["telegram_client_id"], ["telegram_client.telegram_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_client_proxy")
    op.drop_table("telegram_client")
    # ### end Alembic commands ###
