"""Add channel message statistic

Revision ID: fd36ffa275e8
Revises: e2f49e5f56a9
Create Date: 2026-01-21 22:34:47.303534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd36ffa275e8"
down_revision: str | Sequence[str] | None = "e2f49e5f56a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_message_statistic",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["channel_message.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_message_statistic_message_id"),
        "channel_message_statistic",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_channel_message_statistic_message_id"),
        table_name="channel_message_statistic",
    )
    op.drop_table("channel_message_statistic")
    # ### end Alembic commands ###
